language: php

php:
  - '7.3'

services:
  - postgresql

before_script:
  - psql -c "CREATE USER interamnia WITH PASSWORD 'db_password';" -U postgres
  - psql -c "CREATE DATABASE interamnia;" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE interamnia TO interamnia;" -U postgres

env:
    - DATABASE_URL="pgsql://interamnia:db_password@127.0.0.1:5432/interamnia"

script:
   - composer install
   - php bin/console doctrine:migrations:migrate -n
   - php bin/console doctrine:fixtures:load -q
   - php bin/phpunit
